routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->prefix('admin')->namespace('Backend')->name('admin.')->group(function(){
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/chat', 'ChatController@index')->name('chat.index');
    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::post('/setting/store', 'SettingController@store')->name('setting.store');
    Route::post('/setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
    Route::post('/setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');
    Route::post ('/message_send', 'BotController@send_answer')->name('send_answer');
    Route::get('/task', function (){

        return view('backend.task.index', [
            'task' => array(1,2,3,4,6,7)
        ]);
    })->name('task');
});

Auth::routes();

Route::post('/' . config('telegram.bot_token'), 'Backend\BotController@command');



Route::match(['get','post'], 'register', function(){
    Auth::logout();
    return redirect('/');
})->name('register');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/BotController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Events\ChatMessageWasReceived;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Telegram\Bot\Api;
use Telegram\Bot\Laravel\Facades\Telegram;

class BotController extends Controller
{

    protected $telegram;

    public function __construct(Api $telegram)
    {
        $this->telegram = $telegram;
    }
    public function command(Request $request)
    {
        $update = $this->telegram->commandsHandler(true);
        $message = $update->getMessage();
        $user = new User();
//        if (str_contains($message->getText(), ['Хочу фильм'])) {
//            $this->telegram->sendChatAction(['action' => 'typing', 'chat_id' => $message->getChat()->getId()]);
//            for ($i = 1; $i <= 999; $i++) {
//                $endpoint = 'http://api.themoviedb.org/3/movie/' . rand(1, 999);
//                $client = new \GuzzleHttp\Client();
//                $result = $client->get($endpoint, ['query' => [
//                    'api_key' => '910f3a38f0d5aa1263fc8915b1461c5e',
//                    'language' => 'ru',
//                ]]);
//                $content = json_decode($result->getBody()->getContents());
//                if (!empty($content->belongs_to_collection->name)) {
//                    $this->telegram->sendMessage(['text' => $content->belongs_to_collection->name, 'chat_id' => $message->getChat()->getId()]);
//                    $this->telegram->sendPhoto(['chat_id' => $message->getChat()->getId(), 'photo' => 'https://image.tmdb.org/t/p/w500'.$content->belongs_to_collection->poster_path]);
//                    break;
//                }
//            }
//        }

//        $text =  $user->messages()->create([
//            'customer_id' => $message->getChat()->getId(),
//            'message' => $message->getText()
//        ]);
//        $this->telegram->sendMessage(['text' => 'Ожидайте, скоро с вами свяжется наш сотрудник', 'chat_id' => $message->getChat()->getId()]);
        event(new ChatMessageWasReceived($update->getMessage()->getText(), $update->getMessage()->getChat()->getId()));

    }

    public function send_answer(Request $request){
         $this->telegram->sendMessage(['text' => $request->input('message'), 'chat_id' => $request->input('chat_id')]);
    }
}


app/Http/Controllers/Backend/ChatController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChatController extends Controller
{
    public function index(){
        return view('backend.chat.index');
    }
}

app/Http/Controllers/Backend/CustomersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Backend\Customers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Backend\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function show(Customers $customers)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Backend\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function edit(Customers $customers)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Backend\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customers $customers)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Backend\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customers $customers)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Backend\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class SettingController extends Controller
{
    public function index(){

        return view('backend.setting', Setting::getSettings());
    }
    public function store(Request $request){
        Setting::where('key', '!=', NULL)->delete();
        
        foreach($request->except('_token') as $key => $value){
                $setting = new Setting();
                $setting->key = $key;
                $setting->value = $request->$key;
                $setting->save();
        }
        return redirect()->route('admin.setting.index');
    }
    public function setwebhook(Request $request){
        $result = $this->sendTelegramData('POST','setwebhook', [
            'query' => ['url' => $request->url .'/' . \Telegram::getAccessToken()]
            ]);
            
        return redirect()->route('admin.setting.index')->with('status', $result);    
    }
    public function getwebhookinfo(Request $request){
        $result = $this->sendTelegramData('POST','getwebhookinfo');
        return redirect()->route('admin.setting.index')->with('status', $result);    
    }
    public function sendTelegramData($method = 'POST', $route = '', $params = [] ){

        $client = new \GuzzleHttp\Client(['base_uri' => 'https://api.telegram.org/bot' . \Telegram::getAccessToken() . '/' ]);

        $result = $client->request($method, $route, $params);

        return (string)$result->getBody();
    }
}

resources/views/backend/index.blade.php
@extends('backend.layouts.app')

@section('content')



    @endsection

resources/views/backend/setting.blade.php
@extends ('backend.layouts.app')

@section('content')
<div class="container">
    @if(Session::has('status'))
        <div class="alert alert-info">
            <span>{{ Session::get('status') }}</span>
        </div>
    @endif
    <form action="{{ route('admin.setting.store') }}" method="post">
         <div class="form-group">
             <label for="">Url callback for Bot</label>
             <div class=input-group>
                 <div class="input-group-btn">
                     <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Event <span class="caret"></span>
                     </button>
                     <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                         <li class="dropdown-item"><a href="#" onclick="document.getElementById('url_callback_bot').value = {{ url('') }}">Paste Url</a></li>
                         <li class="dropdown-item"><a href="#" onclick="event.preventDefault(); document.getElementById('setWebHook').submit()" >Send Url</a></li>
                         <li class="dropdown-item"><a href="#" onclick="event.preventDefault(); document.getElementById('getWebHookInfo').submit()">Get Information</a></li>
                     </ul>
                 </div>
                 <input type="text" class="form-control" id="url_callback_bot" name="url_callback_bot" value="{{ $url_callback_bot ?? '' }}" />
             </div>
         </div>
        @csrf
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
    <form id="setWebHook" action="{{ route('admin.setting.setwebhook') }}" method="POST" style="display:none">
        @csrf
        <input type="hidden" name="url" value="{{ $url_callback_bot ?? '' }}" />
    </form>
      <form id="getWebHookInfo" action="{{ route('admin.setting.getwebhookinfo') }}" method="POST" style="display:none">
        @csrf
    </form>
</div>

@endsection